//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RectTable
    {
        public System.Guid CompanyID { get; set; }
        public string FeatureName { get; set; }
        public string RectType { get; set; }
        public string strPoints { get; set; }
        public string Remark { get; set; }
        public System.DateTime LastEditTime { get; set; }
        public string SetTime { get; set; }
        public Nullable<int> FloatingTime { get; set; }
        public string NeedCorrect { get; set; }
        public Nullable<bool> IsStatic { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string RunningNo1 { get; set; }
        public string RunningNo2 { get; set; }
        public string ImagePath { get; set; }
        public string BackgroundColor { get; set; }
        public int id { get; set; }
    }
}
