//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cx13000000003
    {
        public System.DateTime Time { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public int Velocity { get; set; }
    }
}
